project:
  type: website
  output-dir: _site
  
#date: today
#date-format: "YYYY"

website:
  #google-analytics: ""
  cookie-consent: true
  title: "Cloud-SPAN Metatranscriptomics"
  favicon: images/cloud-span-icon.png
  page-navigation: true         # prev and next options at the bottom of each page
  back-to-top-navigation: true
  reader-mode: true  
  repo-url: https://github.com/Cloud-SPAN/metatranscriptomics
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2021–24 by [Cloud-SPAN](https://cloud-span.york.ac.uk/)    
#      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2021–{{<meta date>}} by [Cloud-SPAN](https://cloud-span.york.ac.uk/)\
#      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2018–{{<meta date>}} by the [Carpentries](https://carpentries.org/)\
#      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2016–2018 by the [Data Carpentry](https://datacarpentry.org/)      
    # center:
    #   - text: "About"
    #     href: about.qmd
    #   - text: "FAQ"
    #     href: docs/faq/index.qmd
    #   - text: "License"
    #     href: license.qmd
    #   - text: "Trademark"
    #     href: trademark.qmd
    right:
      - icon: twitter
        href: https://twitter.com/SpanCloud
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/Cloud-SPAN/metatranscriptomics
        aria-label: Quarto GitHub
      # - icon: rss
      #   href: https://quarto.org/docs/blog/index.xml
      #   aria-label: Quarto Blog RSS
  navbar:
    background: lightblue
    logo: images/cloud-span-icon.png
    logo-alt: "Cloud-SPAN logo."
    title: false
    collapse-below: lg
    left:
      - text: Home  
        href: index.qmd
      - text: Precourse Instructions
        href: docs/miscellanea/precourse-instructions.qmd
      - text: About
        href: docs/miscellanea/about.qmd
#       - text: License
#         href: docs/miscellanea/license.qmd
#       - text: Code of Conduct
#         href: docs/miscellanea/codeofconduct.qmd
#       - text: Help
#        menu:
#          - text: "Report a Bug"
#            icon: "bug"
#            href: "https://github.com/quarto-dev/quarto-cli/issues"
#          - text: "Ask a Question"
#            icon: "chat-right-text"
#            href: "https://github.com/quarto-dev/quarto-cli/discussions"
#          - text: "FAQ"
#            icon: "question-circle"
#            href: docs/faq/index.qmd
  
  sidebar:
    style: "docked"
    collapse-level: 1
    pinned: true
    contents:
      - section: Files and Directories
        href: docs/lesson01-files-and-directories/index.qmd
        contents: 
          - docs/lesson01-files-and-directories/01-understanding-file-systems.qmd 
          - docs/lesson01-files-and-directories/02-logging-onto-cloud.qmd
          - docs/lesson01-files-and-directories/03-shell-introduction.qmd
      - section: "Using the Command Line"
        href: docs/lesson02-using-the-command-line/index.qmd
        contents: 
          - docs/lesson02-using-the-command-line/01-navigating-file-directories.qmd
          - docs/lesson02-using-the-command-line/02-working-with-file.qmd
          - docs/lesson02-using-the-command-line/03-redirection.qmd
      - section: "QC & RNA pre-processing"
        href: docs/lesson03-qc-pre-processing/index.qmd
        contents: 
          - docs/lesson03-qc-pre-processing/01-introduction-meta.qmd
          - docs/lesson03-qc-pre-processing/02-QC-raw-reads.qmd
          - docs/lesson03-qc-pre-processing/03-rrna-filtering.qmd
      - section: "Taxonomic Annotation"
        href: docs/lesson04-taxonomic-annotation/index.qmd
        contents: 
          - docs/lesson04-taxonomic-annotation/01-community-structure.qmd
          - docs/lesson04-taxonomic-annotation/02-visualising-structure.qmd
      - section:  "Functional Annotation"
        href: docs/lesson05-functional-annotation/index.qmd
        contents: 
          - docs/lesson05-functional-annotation/01-functional-info.qmd
          - docs/lesson05-functional-annotation/02-normalising-and-identifying.qmd
      - section: "Combining Annotations"
        href: docs/lesson06-combining-annotations/index.qmd
        contents: 
          - docs/lesson06-combining-annotations/01-combining-annotations.qmd
          - docs/lesson06-combining-annotations/02-Diversity-tackled-with-R.qmd
          - docs/lesson06-combining-annotations/03-hands_on-diversity.qmd
      - section: "Extras"
        contents: 
          - docs/miscellanea/extras/data.qmd
          - docs/miscellanea/extras/glossary.qmd
          - docs/miscellanea/extras/workflow.qmd

format:
  html:
    code-copy: true
    # highlight-style: oblivion, haddock or monochrome # dracula # espresso #(nice greyish)
    highlight-style: dracula
    code-overflow: wrap
    page-layout: full
    theme: cosmo
    css: styles.css
#    theme:
#    - styles.scss
    toc: true
    grid:                     # defaults
      sidebar-width: 230px    # 300px
      body-width: 1040px      # 900px
      margin-width: 230px     # 300px
      gutter-width: 1.5rem    # 1.5rem
    lang: en
    keywords: transcriptomics, cloud computing, AWS, command line tools, data analysis, environmental science, learning resource
    license: CC BY
    appendix-style: none
    title-block-style: none
    
execute:
  freeze: auto

editor: visual

