---
title: "Metatranscriptomics"
# title-block-banner: true
---

This hands-on, online course teaches data analysis for metatranscriptomics projects. It is aimed at those with little or no experience of using high performance computing (HPC) for data analysis. In the course we will cover:

-   navigating file directories and using the command line
-   logging into a remote cloud instance
-   using common commands and running analysis programs in the command line
-   what is metatranscriptomics?
-   following a metatranscriptomics analysis workflow including:
    -   Perform quality control on RNA-seq reads

    -   Carry out adapter trimming and quality filtering

    -   Remove rRNA sequences from RNA-seq data

    -   Merge and prepare reads for downstream analyses

    -   Perform taxonomic profiling of metatranscriptomic data

    -   Functionally interpret expressed genes

    -   Visualise and explore results using interactive tools such as Krona

The course is taught as a mixture of live coding, online lectures, self-study and drop-in sessions.

## Prerequisites

::: callout-important
## Biological concepts and software setup

This course assumes no prior experience with the tools covered in the workshop but learners are expected to have some familiarity with biological concepts, including the concept of genomes and microbiomes. Participants should bring their own laptops and plan to participate actively.

To get started, follow the directions in the "Precourse Instructions" tab to get access to the required software and data for this workshop. **Windows users** need to install Git Bash in their laptop. **Mac users** may need to configure the **terminal** program in their laptop to use the Bash shell.
:::

## Data

::: callout-note
## About the data used in the course

This course uses data from the Galaxy Training Network tutorial on metatranscriptomics, which utilizes a dataset hosted on Zenodo ([Kunath et al., 2018, ISME J](https://academic.oup.com/ismej/article/13/3/603/7475213)). The dataset comes from a time-series analysis of a microbial community inside a bioreactor. For the purposes of this course, we focus on a single time point (the first) and one biological replicate (replicate A). The data consist of paired-end RNA-Seq sequences in FastQ format, representing the expressed functional potential of the microbial community.

The samples originate from a **cellulose-degrading microbial consortium (SEM1b)** enriched from a thermophilic biogas reactor in Norway. The consortium is co-dominated by *Clostridium thermocellum*, a cellulolytic bacterium, and multiple strains of *Coprothermobacter proteolyticus*, which together degrade plant biomass under anaerobic, high-temperature conditions. This enrichment was performed to study the active expression of carbohydrate-degrading genes within the community.
:::

## Course format

This workshop is designed to be run on pre-imaged Amazon Web Services (AWS) instances. All the software and data used in the workshop are hosted on an Amazon Machine Image (AMI). We will give you details as to how to access these instances after registration.

The course will take place over three weeks and will combine live coding and teaching with offline work. We will guide you through the analysis each session but some steps may need to completed offline due to the amount of time they take to complete. There will also be drop-in sessions to offer support and troubleshooting help, and a Slack workspace for questions.

<!-- ## Course Overview -->

<!-- | Lesson | Overview | -->

<!-- |-----------------------------|-------------------------------------------| -->

<!-- | [Files and Directories](docs/lesson01-files-and-directories/index.qmd) | Learn about files and directories, log onto a cloud instance and get a basic introduction to the shell. | -->

<!-- | [Using the Command Line](docs/lesson02-using-the-command-line/index.qmd) | Learn more about using the shell to navigate directories, manipulate and search files, and combine existing commands to do new things. | -->

<!-- | [QC & Pre-Processing](docs/lesson03-qc-pre-processing/index.qmd) | How to quality control raw RNA reads and prepare them for further analysis. | -->

<!-- | [Taxonomic Annotation](docs/lesson04-taxonomic-annotation/index.qmd) | How to extract the community profile from RNA reads. | -->

<!-- | [Functional Annotation](docs/lesson05-functional-annotation/index.qmd) | How to find out which genes and pathways are present in our community. | -->

<!-- | [Combining Annotations](docs/lesson06-combining-annotations/index.qmd) | How to combine taxonomic and functional annotations for deeper understanding. | -->

<!-- | [Automating Analyses with Bash Scripts](docs/lesson07-automation-bash-scripts/index.qmd) | How to automate the analyses tasks in the previous lessons using Bash scripts. | -->
