---
title: "Using the Command Line"
#subtitle: "[Metagenomics](/index.qmd)"
# title-block-banner: true
---

Welcome to the second lesson of our **Metagenomics with High Performance Computing** course.

In this lesson we will continue learning the foundational command line skills needed for metagenomics analysis. We will recap how to navigate our cloud-based file system, learn how to work with files and discover how combining commands can unlock new possibilities.

#### By the end of this lesson you will be able to:

- Perform operations on files in directories outside your working directory.
- Be comfortable using absolute and relative paths.
- View, search within, copy, move, and rename files, and create new directories.
- Use wildcards (`*`) to perform operations on multiple files.
- Use the `history` command to view and repeat recently used commands.
- Employ the `grep` command to search for information within files.
- Print the results of a command to a file.

::: callout-note
## Getting Started

This lesson assumes no prior experience with the tools covered in the module. However, learners are expected to have some familiarity with biological concepts.

Participants should bring their laptops and plan to participate actively.

Before starting this lesson, you should make sure you have fully covered the [Files and Directories](/docs/lesson01-files-and-directories/index.qmd) lesson.
:::
