---
title: "Visualising Community Structure"
---

## Visualising the Taxonomic Profile

Last episode we used Metaphlan to output a table of the community structure of our metatranscriptome. Whilst this is somewhat human readable, it can be much easier to interpret by visualising the data in graph form. This is especially true of outputs with more taxa than ours, which only had taxa that could be resolved to species level and below.

### Interactive plots with Krona

Krona [(Ondov et al. 2011)](https://ondovb.github.io/portfolio/01-krona) renders your Metaphlan output into a zoomable, multi-layered pie chart, and allows for hierarchical data (in our case taxonomic levels) to be explored.

In order to create a Krona plot we can use a tool to convert our output into a Krona-ready input. This tool is conveniently called `metaphlan2krona`. The command to use it is simple and looks like this:

``` {.bash filename="Code"}
metaphlan2krona.py -p analysis/metaphlan/metaphlan_output.txt -k analysis/metaphlan/metaphlan.krona.txt
```

Run this command and wait a few seconds for it to run. For our table it should only take a few moments, but on larger tables it could take a little longer.

Once our `metaphlan.krona.txt` file is generated we can then feed that directly into Krona, using:

``` {.bash filename="Code"}
ktImportText analysis/metaphlan/metaphlan.krona.txt -o analysis/krona.html
```

This will also only take a short few moments to process.

Once it has ran you should be able to see `krona.html` in your `analysis/` directory. Unfortunately we cannot view html files using the command line, and so we shall instead have to download it to your local computer.

First, open up gitbash in your CloudSPAN folder. Then we shall use the "secure copy" or `scp` function to download the file from your instance using this command:

``` {.bash filename="Code"}
scp -i login-key-instanceXXX.pem csuser@instanceXXX.cloud-span.aws.york.ac.uk:~/cs_course/analysis/krona.html .
```

replacing XXX with your instance number. Much like cp or mv commands, this is telling the command where to copy from (`csuser@instanceXXX.cloud-span.aws.york.ac.uk:~/cs_course/analysis/krona.html`) and then where to copy to (remember, the `.` means current working directory).

If you are struggling to get the download to work, don't worry, you can access a copy of it [here](/files/krona.html).

You may notice that the sections of the pie chart are incorrectly labelled with abundances rather than taxa names. This is because Krona expects all levels of taxonomy when generating the chart and has misread the abundances as a label also. To see more of a "real world" example we shall now look at the output of a Metaphlan run that captured all taxonomic levels (the `--tax_lev` flag set to `a` for "all").

#### Generating a more detailed Krona plot

We have hidden a pre-ran Metaphlan all levels output in your data folder in a hidden directory, `data/.fullmetaphlanrun`. You can process this with Krona in the same way as before:

``` {.bash filename="Code"}
ktImportText data/.fullmetaphlanrun/metaphlan_fulltaxaoutput.krona.txt -o analysis/krona_alltaxa.html
```

Now you can download it from our instance to your local computer, again using `scp`:

``` {.bash filename="Code"}
scp -i login-key-instanceXXX.pem csuser@instanceXXX.cloud-span.aws.york.ac.uk:~/cs_course/analysis/krona_alltaxa.html .
```

Once again, substituting XXX for your instance number. Again if you're struggling to get this to work, don't worry, you can find a copy of it [here](/files/krona_alltaxa.html).

As you can see tise plot is in much greater detail than our previous one. You can click on the different sections to see summaries of the abundances at different levels, as well as double click on a section to zoom into the sub-structure that particular clade (you can use the back and forward arrows at the top left to navigate back and forward).

:::: callout-note
From the interactive Krona figure, try and answer these questions:

1.  What are the % abundances of the Coprothermobacterota and Firmicutes phyla respectively?

2.  What is the % abundance of the SGB8555 strain of *Coprothemobacter proteolyticus*?

::: {.callout-caution collapse="true"}
## Solution

1. 71% and 16%

2. 10%

:::
::::

Because Krona outputs are portable .html files these can be sent to collaborators or uploaded for others to browse.

## Setup for next session

If you are working through this course as a self-study exercise, you can ignore this section and proceed to the next lesson for an in-depth explanation before you set any commands running.
If you are participating in one of our online Zoom courses, you will want to set the below commands running at the end of this session so Humann has time to run!

``` {.bash filename="Code"}
mkdir -p analysis/humann
```

``` {.bash filename="Code"}
humann --input analysis/sortmerna/SRR6820491_mrna.fq \
--output analysis/humann/ \
--taxonomic-profile analysis/metaphlan/metaphlan_output.txt \
--threads 8 \
&> analysis/humann/log.txt &
```

Don't worry about quite what this does yet, this shall be explained more fully in the next lesson!