---
title: "Taxonomic Annotation"
#subtitle: "[Metatranscriptomics](/index.qmd)"
# title-block-banner: true
---
<!-- ---
layout: lesson
root: .
--- -->
Welcome back to this **Metagenomics with High Performance Computing** course!

In previous lessons, we preprocessed our RNA-seq data by assessing read quality, trimming adapters, and removing unwanted sequences. This prepared our dataset for downstream analyses.

One of the first major steps in metatranscriptomics is to understand the community composition: which organisms are present in the sample and in what relative abundances. This is called taxonomic profiling. Tools like MetaPhlAn allow us to map reads to clade-specific marker genes to generate a profile of the microbial community. Once we have this profile, we can also visualize it interactively using tools like Krona or generate publication-ready figures with Graphlan.

By the end of this lesson you will be able to:

- explain what community profiling is and why it is important
- run MetaPhlAn to extract the taxonomic composition of a sample 
- interpret the main MetaPhlAn output, including relative abundances at different taxonomic levels
- visualize the microbial community interactively with Krona